### ISSUE TITLE
[Request] Need an alternative package for LIEF

### ISSUE THREAD

**Issue by bruce30262** [Jinmo/idapkg#16]
Starting from version [0.10.0](https://github.com/lief-project/LIEF/releases) LIEF had dropped the support for Python 2.7. Since idapkg will install the latest version of LIEF this will results in installation error if the user is using IDA before version 7.4 ( = no Python 3 support ).  

Right now a dirty fix is to bind the version of LIEF to 0.9.0 ( `python -m pip install lief==0.9.0` will resolve the issue ). However I think it is necessary to find an alternative package for LIEF ( e.g. katai struct like you mentioned in #10 ). The package should be Python2/3 compatible if possible, since not everyone has the latest version of IDA :P

**Comment by Jinmo** [comment]
463e523 does
- support python 3
- remove lief, uses bundled kaitai struct (it was quite better than I expected...)

One concern is, if a plugin only supports python 2 or 3, then there should be a kind of indicator.
Maybe now is the time that something like _win_py27 should be implemented... :)

**Comment by Jinmo** [comment]
Resolved in v0.1.4!
