### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by bruce30262** [Jinmo/idapkg#17]
## ENV
OS: Windows 10
Python: 3.8.5
IDA version: 7.5
IDAPython: v7.4.0  
idapkg : 0.1.4

## Detail
While installing idapkg, the install command shows the following warning message:

```
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:94: SyntaxWarning: "is" with a literal. Did you mean "=="?
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:94: SyntaxWarning: "is" with a literal. Did you mean "=="?
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:100: SyntaxWarning: "is" with a literal. Did you mean "=="?
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:94: SyntaxWarning: "is" with a literal. Did you mean "=="?
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:94: SyntaxWarning: "is" with a literal. Did you mean "=="?
idapkg-0.1.4\pkg\vendor\semantic_version\base.py:100: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
It seems to install idapkg successfully, however the warning messages' kind of annoying  

I think the `SyntaxWarning` message was introduced in Python 3.8
Changing `is` to `==` should fix the problem

**Comment by Jinmo** [comment]
Thanks for reporting! I'll update bundled dependency: python-semanticversion, which now seems to resolve this issue.
