### ISSUE TITLE
Cannot login to idapkg.com & not able to access repo

### ISSUE THREAD

**Issue by bruce30262** [Jinmo/idapkg#21]
As titled, I found that I cannot login to idapkg.com ( it says "Network error" on the web page ). Also I wasn't able to access the repo page ( e.g. https://idapkg.com/p/PythonEditor ). Is everything OK ?

**Comment by Jinmo** [comment]
Hello, it seems like I accidently disabled the server when migrating.
However, since no one is now using idapkg, it might be a good timing to archive the project..
Farewell idapkg :innocent: and thank you for your interest on this subject :bow:.

**Comment by bruce30262** [comment]
That's unfortunate...I really like idapkg, and I use it quite frequently. It makes installing IDA plugins really convenient, the best thing is that you don't even have to re-install the plugin after updating IDA to a new version, which makes the updating process less painful. I'll be really sad if the project is discontinued...😢.

In case idapkg.com no longer exists:
1. For hosting our own idapkg.com, will [idapkg-website](https://github.com/Jinmo/idapkg-website) be enough ? Or do we also need things in [idapkg-api](https://github.com/Jinmo/idapkg-api) ? ( I'm not sure what idapkg-api is about though 😬). I think a docker image would be nice.
2. It seems that we can also install plugins from github in idapkg ( [idapkg-repo](https://github.com/Jinmo/idapkg-repo) ).  
    a. Can we install plugins from a private github repo ( or private GitLab repo )  ?  If so, is there any documentation on how to do this ?
    b. Will APIs like `pkg.install`, `pkg.upgrade` also work for those plugins that are installed from github instead of idapkg.com ?

Thank you for creating this amazing project, it's a shame that very few people are using this 😔

**Comment by Jinmo** [comment]
Sorry for the delays.

1.
  - idapkg-website is the frontend, which emits a static website that connects to idapkg-api based web server. Actually, idapkg-website was hosted via AWS S3 (=idapkg.com).
  - idapkg-api is the backend which allows user registration/package management/etc (=api.idapkg.com).

2.
  - a. github connector is [based on](https://github.com/Jinmo/idapkg/blob/5d6af9bd59c5dc886d68335119fae41491f06ea7/pkg/repo.py#L139) raw.githubcontent.com downloads, so repo needs ot be public for now. (If it can be served via github pages, supporting private repo might be doable)
  - b. I think so.

**Comment by bruce30262** [comment]
Thanks for replying ! Here are some of my thoughts :

For self hosting idapkg, it would be nice if you can add some documentations of how to set up idapkg-website & idapkg-api, a ready-for-deployment docker image would be even nicer !

As for installing from private github repo, I think a downloader with access token support should also do the trick. With access token we can even install the plugin from a private gitlab repo.

Of course things mentioned above all depends on you -- you do that whenever you have time and interest 🙂. Meanwhile I think I'm gonna spent some time and learn how to host them myself.

**Comment by bruce30262** [comment]
Closing issue due to discontinuation of the project
